version: 2  # обязательно! текущая версия конфигурации

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - third_party
    - migrations

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - errcheck
    - dupl
    - nakedret

issues:
  exclude-rules:
    - path: '_test\.go'
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0